variables:
  DOCKER_PASSWORD: $DOCKER_PASSWORD
  DOCKER_REGISTRY: docker.example.com
  DOCKER_USER: docker
  DOCKER_NAME: luarocks-artifactory
  DOCKER_TAG: latest
  ARTIFACTORY_URL: https://repo.example.com/artifactory

stages:
  - build

my-luarocks.snapshot:
  tags:
    - repo.example.com
  stage: build
  image: docker:latest
  script:
    - pwd
    - docker pull $DOCKER_REGISTRY/$DOCKER_NAME:$DOCKER_TAG
    - docker run --rm --device /dev/fuse -v`pwd`:/src --privileged $DOCKER_REGISTRY/$DOCKER_NAME:$DOCKER_TAG
      sh /src/create-luarocks.sh $ARTIFACTORY_URL $CI_JOB_NAME $DEPLOY_CI_AUTH --packages penlight

docker build:
  stage: build
  when: manual
  image: docker:latest
  before_script:
    - docker info
  script:
    - docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_REGISTRY/$DOCKER_NAME:$DOCKER_TAG .
    - docker push $DOCKER_REGISTRY/$DOCKER_NAME:$DOCKER_TAG
